### ISSUE TITLE
Make ads depend on campaigns

### ISSUE THREAD

**Issue by andresionek91** [andresionek91/fake-web-events#3]
Campaigns should be one level above on hierarchy than ads. Something like this:
```yml
campaigns:
  campaign_a:
    ad_1: 0.25
    ad_2: 0.25
  campaign_b:
    ad_3: 0.25
    ad_4: 0.25
```

Meaning that one add is linked to a specific campaign when running the simulation. Right now the simulation will pick a random ad and a random campaign. 

Some users should also come without ad or campaign associated to simulate direct access.
